baseURL = "https://siegristlk.github.io/portfolio/"
title = "Lisa Siegrist"
languageCode = "de"
defaultContentLanguage = "de"
defaultContentLanguageInSubdir = true


[module]
[module.hugoVersion]
extended = true


## Commented as per https://github.com/zetxek/adritian-free-hugo-theme/discussions/158#discussioncomment-11916561
# [[module.imports]]
# ignoreConfig = true
# path = "github.com/twbs/bootstrap"
# [[module.imports.mounts]]
# source = "scss"
# target = "assets/scss/bootstrap"
# [[module.imports.mounts]]
# source = "js"
# target = "assets/js/bootstrap"
# [[module.imports]]
# path = "github.com/gohugoio/hugo-mod-jslibs-dist/popperjs/v2"


publishDir = "docs"

[caches]
  [caches.images]
    dir = ':cacheDir/images'

[markup.goldmark.renderer]
unsafe = true

_merge = "deep"

[[module.imports]]
path = "github.com/zetxek/adritian-free-hugo-theme"

## Base mounts - so your site's assets are available
[[module.mounts]]
source = "archetypes"
target = "archetypes"

[[module.mounts]]
source = "assets"
target = "assets"

[[module.mounts]]
source = "i18n"
target = "i18n"

[[module.mounts]]
source = "layouts"
target = "layouts"

[[module.mounts]]
source = "static"
target = "static"

# The following mounts are required for the theme to be able to load bootstrap
# Remember also to copy the theme's `package.json` to your site, and run `npm install`
[[module.mounts]]
source = "node_modules/bootstrap/scss"
target = "assets/scss/bootstrap"

[[module.mounts]]
source = "node_modules/bootstrap/dist/js"
target = "assets/js/bootstrap"

[[module.mounts]]
source = "node_modules/bootstrap/dist/js/bootstrap.bundle.min.js"
target = "assets/js/vendor/bootstrap.bundle.min.js"

[[module.mounts]]
source = "node_modules/bootstrap-print-css/css/bootstrap-print.css"
target = "assets/css/bootstrap-print.css"


[params]
title = 'Lisa Siegrist | Digital Learning Developer & Instructional Designer'
description = 'Personal Site for Lisa Siegrist'
customCSS = ["css/custom.css"]


# If you want to display an image logo in the header, you can add it here
# logo = '/img/hugo.svg'

homepageExperienceCount = 6

[params.analytics]
## Analytics parameters.
### Supported so far: Vercel (Page Insights, Analytics)
### And Google (Tag Manager, Analytics)

# controls vercel page insights - disabled by default
# to enable, just set to true
vercelPageInsights = false
vercelAnalytics = false

# google analytics and tag manager. to enable, set "enabled" to true
# and add the tracking code (UA-something for analytics, GTM-something for tag manager)
[params.analytics.googleAnalytics]
code = "UA-XXXXX-Y"
enabled = true
[params.analytics.googleTagManager]
code = "GTM-XXXXX"
enabled = false

[build]
writeStats = true

[build.buildStats]
enabledFor = ["scss"]
disableClasses = false
disableIDs = false
disableTags = false
enable = true

[params.languages.selector.disable]
footer = false
header = false
mobileHeader = false

[languages]
[languages.en]
disabled = false
languageCode = 'en'
languageDirection = 'ltr'
languageName = 'English'
title = ''
weight = 0

[languages.en.menus]
[[languages.en.menus.header]]
name = "Home"
URL = "/en/"
weight = 1

[[languages.en.menus.header]]
name = 'About'
URL = '/en/#about'
weight = 2

[[languages.en.menus.header]]
name = "Education"
URL = "/en/#education"
weight = 3

[[languages.en.menus.header]]
name = "Experience"
URL = "/en/#experience-single"
weight = 4

[[languages.en.menus.header]]
name = "Projects"
URL = "/en/#client-and-work-section"
weight = 5

[[languages.en.menus.header]]
name = "Blog"
URL = "/en//blog"
weight = 6

[[languages.en.menus.header]]
name = "Contact"
URL = "/en/#contact"
weight = 7

[languages.fr]
disabled = true
languageCode = 'fr'
languageDirection = 'ltr'
languageName = 'Français'
title = ''
weight = 0

[languages.fr.menus]
[[languages.fr.menus.header]]
name = "ACCUEIL"
URL = "/fr/"
weight = 1
[[languages.fr.menus.header]]
name = 'About'
URL = '/fr/#about'
weight = 2

[[languages.fr.menus.header]]
name = "Experience"
URL = "/fr/#experience-single"
weight = 3

[[languages.fr.menus.header]]
name = "Blog"
URL = "/fr/blog"
weight = 4

[[languages.fr.menus.header]]
name = "Contact"
URL = "/fr/#contact"
weight = 5


[languages.de]
disabled = false
languageCode = 'de'
languageDirection = 'ltr'
languageName = 'Deutsch'
title = ''
weight = 0

[[languages.de.menus.header]]
name = "Startseite"
URL = "/de/"
weight = 1

[[languages.de.menus.header]]
name = 'Über mich'
URL = '/de/#about'
weight = 2

[[languages.de.menus.header]]
name = "Bildungsweg"
URL = "/de/#education"
weight = 3

[[languages.de.menus.header]]
name = "Erfahrungen"
URL = "/de/#experience-single"
weight = 4

[[languages.de.menus.header]]
name = "Meine Projekte"
URL = "/de/#client-and-work-section"
weight = 5

[[languages.de.menus.header]]
name = "Blog"
URL = "/de/blog"
weight = 6

[[languages.de.menus.header]]
name = "Kontakt"
URL = "/de/#contact"
weight = 7




# Plugins
[params.plugins]

# CSS Plugins
[[params.plugins.css]]
URL = "css/custom.css"
[[params.plugins.css]]
URL = "css/adritian-icons.css"
## Print css
[[params.plugins.css]]
URL = "css/bootstrap-print.css"
[[params.plugins.css]]
    Sass = "scss/books.scss"

# JS Plugins
[[params.plugins.js]]
URL = "js/rad-animations.js"
[[params.plugins.js]]
URL = "js/sticky-header.js"
[[params.plugins.js]]
URL = "js/library/fontfaceobserver.js"

# SCSS Plugins
[[params.plugins.scss]]
URL = "scss/adritian.scss"
[[params.plugins.scss]]
URL = "scss/books.scss"

  

# theme/color style 
[params.colorTheme]

## the following configuration would disable automatic theme selection
#  [params.colorTheme.auto]
#    disable = true
#  [params.colorTheme.forced]
#    theme = "dark"

## the following parameter will disable theme override in the footer
#  [params.colorTheme.selector.disable]
#  footer = true


[params.colorTheme.selector.disable]
footer = false
header = false
mobileHeader = false
## by default we allow override AND automatic selection

[params.blog]
layout = "sidebar-right"     # options: default (no sidebar), sidebar, sidebar-right
sidebarWidth = "25"    # percentage width of the sidebar
showCategories = true
showRecentPosts = true
recentPostCount = 5
listStyle = "summary"  # options: simple, summary
featured_sort_by_weight = true
featured_sort_by_date = false


[params.experience]
showJobCard = true # Set to false to hide the job card

