name: Build Hugo site into /docs

permissions:
  contents: write

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: 'latest'
          extended: true

      - name: Build site into docs/
        run: hugo -d docs

      - name: Commit built site to main/docs
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add docs
          git diff --cached --quiet || (git commit -m "Rebuild site into /docs" && git push)
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
