name: Build and Deploy Hugo to Codeberg Pages

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy-codeberg:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: 'latest'
          extended: true

      - name: Build site for Codeberg
        run: hugo -d public --baseURL "https://siegristlk.codeberg.page/"


      - name: Setup SSH for Codeberg
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.CODEBERG_DEPLOY_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          ssh-keyscan codeberg.org >> ~/.ssh/known_hosts

      - name: Deploy to Codeberg Pages
        run: |
          cd public
          git init
          git config user.name "GitHub CI"
          git config user.email "ci@github.com"
          git remote add origin git@codeberg.org:siegristlk/pages.git
          git checkout -b main
          git add .
          git commit -m "🚀 Auto deploy to Codeberg Pages"
          git push -f origin main
